🟢Sprint 1 (Importação dos dados): Realização da importação dos dados na plataforma Kaggle para a IDE VsCode ou Colab, onde  o script  será executado
https://www.kaggle.com/datasets/namespaiva/base-varejo?resource=download

Descrição da base de dados:
A base de dados Varejo é um recorte de 50.000 compras de 1.000 clientes realizadas em uma rede de supermercados no período de 2010 à 2022.

1. DATA: Data da compra;
2. CO_ID: Identificação do número de compra (número da nota fiscal);
3. CL_ID: Identificação do cliente (número do cliente);
4. CL_GENERO: Sexo biológico informado pelo cliente;
5. CL_EC: Estado civil do cliente:
    1: Casado ou união estával;
    2: Divorciado;
    3: Separado;
    4. Solteiro;
    5: Viúvo
6. CL_FHL: Número de filhos do cliente;
7. CL_SEG: Segmentação econômica do cliente (classe A, B ou C);
8. PR_ID: Código do produto (SKU) adquirido;
9. PR_CAT: Categoria do produto adquirido;
10. PR_NOME: Nome do produto adquirido.

In [19]:
import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns
from itertools import combinations
from collections import Counter

caminho = os.path.join('database', 'Base Varejo.csv')
df_base_varejo = pd.read_csv(caminho, sep=";")
print(df_base_varejo.info())
df_base_varejo.head()

<class 'pandas.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 14 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   DATA         830000 non-null  str
 1   CO_ID        830000 non-null  int64
 2   CL_ID        830000 non-null  int64
 3   CL_GENERO    830000 non-null  str
 4   CL_EC        830000 non-null  int64
 5   CL_FHL       830000 non-null  int64
 6   CL_SEG       830000 non-null  str
 7   PR_ID        830000 non-null  int64
 8   PR_CAT       830000 non-null  str
 9   PR_NOME      830000 non-null  str
 10  Unnamed: 10  0 non-null       float64
 11  Unnamed: 11  0 non-null       float64
 12  Unnamed: 12  0 non-null       float64
 13  Unnamed: 13  0 non-null       float64
dtypes: float64(4), int64(5), str(5)
memory usage: 88.7 MB
None

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN

🟢Sprint 2 (Transformação de Strings, Integer e Float e Datetime): Desenvolvimento das funções de limpeza de texto, inteiros e decimais usando métodos e expressões regulares.

🟢Sprint 3 (Limpeza de Nulos e Duplicatas): Aplicação das condicionais e funções  para identificação e substituição de valores vazios e  de str para valores de data tipo datetime, na tabela de varejo.

In [20]:
# Tirando as colunas vazias que vieram sobrando
df_base_varejo = df_base_varejo.dropna(axis=1, how='all')

# Ajustando a data e tratando aquele #N/D na categoria
df_base_varejo['DATA'] = pd.to_datetime(df_base_varejo['DATA'], format='%d/%m/%Y', errors='coerce')
df_base_varejo['PR_CAT'] = df_base_varejo['PR_CAT'].apply(lambda x: "Sem Categoria" if x == '#N/D' else x)

# Tirar duplicadas e salvar
antes = df_base_varejo.shape[0]
df_base_varejo = df_base_varejo.drop_duplicates()
depois = df_base_varejo.shape[0]
print(f"Linhas removidas por duplicidade: {antes - depois}")

print("Base carregada e limpa com sucesso.")
df_base_varejo.head()

Linhas removidas por duplicidade: 96553
Base carregada e limpa com sucesso.

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME
0,2019-02-01,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA
1,2019-02-01,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS
2,2019-02-01,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO
3,2019-02-01,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI
4,2019-02-01,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO

In [21]:
print(df_base_varejo.describe())

                             DATA          CO_ID          CL_ID  \
count                      733447  733447.000000  733447.000000
mean   2020-12-06 11:20:27.215055  459941.034680     499.643996
min           2019-01-04 00:00:00    1000.000000       1.000000
25%           2020-01-09 00:00:00  232895.000000     254.000000
50%           2020-12-27 00:00:00  456422.000000     498.000000
75%           2021-10-20 00:00:00  690100.000000     746.000000
max           2022-12-08 00:00:00  919822.000000    1000.000000
std                           NaN  265431.394822     287.561653

               CL_EC         CL_FHL          PR_ID
count  733447.000000  733447.000000  733447.000000
mean        2.597385       1.146049     115.037337
min         1.000000       0.000000       1.000000
25%         2.000000       0.000000      58.000000
50%         3.000000       0.000000     115.000000
75%         4.000000       2.000000     172.000000
max         5.000000       4.000000     229.000000
std         1.170130       1.416917      66.124263

In [22]:
# avaliando os resultados dos valores únicos de cada coluna para limpeza 
# de texto e tratamento de dados faltantes
for coluna in df_base_varejo.columns:
    print(f"--- Valores únicos em: {coluna} ---")
    print(df_base_varejo[coluna].unique())
    print("\n")

--- Valores únicos em: DATA ---
<DatetimeArray>
['2019-02-01 00:00:00', '2019-09-01 00:00:00', '2019-01-13 00:00:00',
 '2019-01-19 00:00:00', '2019-01-23 00:00:00', '2019-01-29 00:00:00',
 '2019-05-02 00:00:00', '2019-06-02 00:00:00', '2019-09-02 00:00:00',
 '2019-02-14 00:00:00',
 ...
 '2022-07-16 00:00:00', '2022-07-17 00:00:00', '2022-07-24 00:00:00',
 '2022-07-30 00:00:00', '2022-07-31 00:00:00', '2022-06-08 00:00:00',
 '2022-12-08 00:00:00', '2022-08-15 00:00:00', '2022-08-17 00:00:00',
 '2022-08-19 00:00:00']
Length: 333, dtype: datetime64[us]


--- Valores únicos em: CO_ID ---
[  1000   1040   1078 ... 919716 919770 919822]


--- Valores únicos em: CL_ID ---
[ 534  279  290  323  957   49  906  653  842  616  406  576  652  453
  829  251  397  438   69  608  423   53  886  624   94  428   72  493
  497  164  689   99  866  801  340   52  574  328  466  296  149  458
  776  746   45  798  709  796  878  888  246  433  545  943  429   56
  922  305  236  193  927  594  333  199  973  686  523  225   82  362
  394  243  160   79  151  933    6  322  663  459  761  384  707  954
  227  804  462  283   25  348  757   44  332   38  257    4  865  982
  516  443  996  847  408  369  502  163  171  597  289  521  770   42
  517  628   59  418  113  756  506  991  773  525  174  498  921  916
   96  110  740  780  350  768  892   75  880  583  580  539  560  645
  978  831  830  651  814  815  301  122  750  802  351  304  143  935
  512  552  759  487  691  828  425  659   17  464  742  884  325   83
  391  785  812  398  206  491  463  510  537  898  482  527    5   34
  971  571  460  551  717  926  951  626  914  735  166  883  710  337
  897  387  245  421  938  115  589   10   15  472  969   39  359  536
  570  766  790  987  684  625  192  630  799  751  396   57   71  310
   20  303  629  455  447  603  734  872  908  960  533  869  524  157
  476  975  577  753  335  752  457  567  392  901  427  389  810  187
  792  657  488  871  448   61  675  965  976  299  368  121  129  956
  565  300  237  994   87  275  444  475  267  222  468  934  591   60
  855  980  188  715  522  473  499  383  200  724  315  614  495  820
  721   70  795  161  634  270  769  140  353  338  863  844  755  964
  550  825  658  655  981  573  469  559  598  218  937  145  819  548
  479  777  179  737  561  618  317  563  696  669  242  306  636  961
   43  319   74  207    3  117  588  532  739  326  791  180  308  673
  390  540  111  641  985  176  316  208  649  349    9  402  664  354
  834   76  741  371   18  442  650  579  238  683  434  695   95  416
  108  248   12  599  596   35  952  656  841  654  609  620  605  484
  955  747  639  440  633  706  822  152  153    7  511  189  562  631
  102  581  602  606  295  729  518  255  441  678  643  586  253  500
  864   32  239  412  414  754  697  950  235  302  285  513  220  902
  470  278  114  419  714  240  214  832  361  229  374  857   97  385
  426   65  970  945  356   30   98  178   91  736  393  341  194  318
  932  928  258  474  342   19  803  896  852  555  217  269  347  942
  575  578  789  451  667  403   63  905  758  846  572  233  541  294
  254  382  879  745  876   68  177  621  286  604  931  613  103  607
   14  437  738  501  170  856  165  936  612   23  807   29  411   81
  209  726  676  329  185  352  967  260  190  672  213  702  264  611
  266  378   21  660  786  230  554  221  334  772  940  924  698  346
  862  210  904  132   11  713  918  211  546  273  247  617  241  196
  853  674  379  784  297  535  644  360  456  704   58  405  873  314
  677  610  716   40  909  324   62  806  701   78  311  490  381  201
  694  363  632  859  903  106  775  670   88  979  298  941  569  818
   41  558  845  584  887  307  147  890  705  136  637   55  107  203
  712   33  204  744  762    2  202   46  528  454  958  109  867  343
  849   31  992  465  259  370  767  615  893  172  700  358  409  870
  925  693  515  282   93  682  116  130  823   85  919  496  778  968
  357  566  984  182  687  719  809  972  430  835  261   28  435  158
  407  821  373  489  331  731   37   73  262  912  119  848   66  413
  228  538  619  191   80  542  483  899  642  911  725  817   16  816
  105  840  367  722  432  824  417  889  372  404  124  366  858  671
  168  793   24  783  156  900  485  723  226  127  813  556  186  948
  590  504  827  646   36  272  794  894  553  252  249  622  508  137
  420   84  718  271  514  291  280  395  313  990  781 1000  120  843
  431  131  445  377  529  276  167  730  480  439  126  478  582  765
  268  231  547  564  592  915  104  983   51  877  974  128  917   54
  123  891  471  690  661  205  648  748  861  339  875  699  601  949
  850  197  881  138  837  680  250   90  154  665  703   48  142  760
  836  800    8  376  774  134  882  422  244  811  364  223  150  256
  234  274  449  593  805  101  503  118  494   47  401  388  692   89
  505  839  424  923  446  963   86  568  929  355  173  284   50  344
  944  595  826  874  782  808  481  486  375  764  519  195  531  763
  141  492  293  910  788  946   26  989  312  436  125  461  162  345
  336  851  380  627   13  277  292  155  112  265   77  215  727  939
  838  640  728  953  530  146  467  988  708  585  638  169  986  452
  662  144  679  450  920  833  685  216  212  600  998  688  666  526
  232  549   67  995  587  281  732  779  135  219  993   64  365  959
  520  681  386  509  320  198  543  913  330  139  749  181  860  668
  733  133  647  224  711  175  159  100  997  966  977  635  771  544
  907  287  797  399  415  507   27  895  410  263  999  148   22  885
    1  947  400  183  309  288  962  720  477  327  930  743  868  854
  623  557   92  321  787  184]


--- Valores únicos em: CL_GENERO ---
<StringArray>
['M', 'F']
Length: 2, dtype: str


--- Valores únicos em: CL_EC ---
[4 1 2 5 3]


--- Valores únicos em: CL_FHL ---
[1 2 0 3 4]


--- Valores únicos em: CL_SEG ---
<StringArray>
['C', 'B', 'A']
Length: 3, dtype: str


--- Valores únicos em: PR_ID ---
[ 67  70 178   4 175 187 163  11  95 198 182  86 221 200  13 218  84 121
 176 136 108  69 143 149  61  64 191 189 135 226 209  52 160 225  56 123
  25 229 155 132  23  24 183  66  68  88  38  94 164  75 145  48  43 134
  19 105 208  60 180 144  99 129 210 192   6 125 156 116 118 107  81  93
  62  14  90 113  36 109  59 215 150 106 173 137   5  49  17  76  30   1
 151 190  44  82  35 162 213 122  21 174  22  39 102  63 172  54 111  78
 146 220  27 212  80 110  51 228   7 126 124 195 154 166 114  42  97  98
 117  53 142 204  85 201 157 141 185  15  87  28  50 171  92 207 184  96
 169 100 217 148  18 223  91  65  32 119 222 128 159 161  12  29 219 115
 206 177 103  55 202 140 214 199  41 170 193 186 101  72 216 138  57 197
 194  45  47 205   3 168  34  77 104 130  79 227  40  26  71 153 139 179
   9 152  10  73  74  16 188 165 127 133 147  83  20 196 158   8  46 203
  58  89 131 120  31   2  37 211 181 167 224  33 112]


--- Valores únicos em: PR_CAT ---
<StringArray>
[      'BEBIDAS',       'HIGIENE',     'ALIMENTOS',       'LIMPEZA',
    'ACESSORIOS',           'PET', 'Sem Categoria']
Length: 7, dtype: str


--- Valores únicos em: PR_NOME ---
<StringArray>
[      'REFRIGERANTE GUARANA',        'REFRIGERANTE OUTROS',
            'LENCO UMEDECIDO',                    'ABACAXI',
          'LIMPADOR MULTIUSO',           'HASTES FLEXIVEIS',
                  'MORTADELA',                     'AZEITE',
                  'AMACIANTE',                 'ENERGETICO',
 ...
                  'HAMBUGUER',      'ALIMENTO PARA PASSARO',
                     'CEBOLA',           'ENXAGUANTE BUCAL',
                      'MANGA', 'COXA E SOBRECOXA DE FRANGO',
                    'ABACATE',                      'ARROZ',
                 'ABSORVENTE',             'MOLHO BARBECUE']
Length: 118, dtype: str

🟢Sprint 4 (Estatística Descritiva): Aplicação das funções estatísticas para coletar parâmetros da coluna de Número de filhos do cliente.

In [25]:
#Gerar estatísticas descritivas básicas para coluna de número de filhos do cliente (média; mediana; desvio padrão; moda; máximo; mínimo; e contagem, quartis)

coluna = 'CL_FHL'
resumo = {
    'Média': df_base_varejo[coluna].mean(),
    'Mediana': df_base_varejo[coluna].median(),
    'Moda': df_base_varejo[coluna].mode()[0],
    'Desvio Padrão': df_base_varejo[coluna].std(),
    'Mínimo': df_base_varejo[coluna].min(),
    'Máximo': df_base_varejo[coluna].max(),
    'Contagem': df_base_varejo[coluna].count()
}
estatisticas = df_base_varejo[coluna].describe()
print(estatisticas)
print()
# Transformar o dicionário em um DataFrame
resumo__estatisticas_df = pd.DataFrame(resumo, index=[0])
print(resumo__estatisticas_df)

count    733447.000000
mean          1.146049
std           1.416917
min           0.000000
25%           0.000000
50%           0.000000
75%           2.000000
max           4.000000
Name: CL_FHL, dtype: float64

      Média  Mediana  Moda  Desvio Padrão  Mínimo  Máximo  Contagem
0  1.146049      0.0     0       1.416917       0       4    733447

🟢Sprint 5 (Relatório e Documentação): Construção dos contadores do relatório final exibido no terminal, finalização do README.md com a reflexão teórica e submissão do link no AVA.

In [16]:
#Explorar padrões de agrupamento com pelo menos dois agrupamentos (por exemplo: gênero com mais vendas, compras), usando groupby() ou pivot_table().

# Cruzamento de Gênero e Segmentação Econômica
perfil_consumo = df_base_varejo_sem_duplicatas.pivot_table(
    index='CL_GENERO', 
    columns='CL_SEG', 
    values='CO_ID', 
    aggfunc='count'
)

print("Volume de compras por Gênero e Classe Econômica")
print(perfil_consumo)
print("\n")

# Cruzamento de Categoria do Produto e Estado Civil
# 1. Primeiro, agrupamos e contamos
df_contagem = df_base_varejo_sem_duplicatas.groupby(['CL_EC_TEXT', 'PR_CAT'])['CO_ID'].count()

# 2. Ordenamos o resultado garantindo que a hierarquia seja mantida
# O comando abaixo ordena o nível dos produtos pela contagem (CO_ID)
interesse_ordenado = df_contagem.groupby(level=0, group_keys=False).apply(lambda x: x.sort_values(ascending=False))

print("Volume de compras por Estado Civil")
print(interesse_ordenado)

Volume de compras por Gênero e Classe Econômica
CL_SEG         A       B       C
CL_GENERO
F          28898  233644  119885
M          30779  234861   85380


Volume de compras por Estado Civil
CL_EC_TEXT               PR_CAT
Casado ou união estável  ALIMENTOS     90143
                         HIGIENE       32287
                         LIMPEZA       30088
                         BEBIDAS        8969
                         PET            6764
                         ACESSORIOS     2993
                         #N/D            766
Divorciado               ALIMENTOS     90379
                         HIGIENE       32172
                         LIMPEZA       30121
                         BEBIDAS        9109
                         PET            6693
                         ACESSORIOS     3006
                         #N/D            803
Separado                 ALIMENTOS     98817
                         HIGIENE       35615
                         LIMPEZA       33218
                         BEBIDAS        9805
                         PET            7372
                         ACESSORIOS     3411
                         #N/D            810
Solteiro                 ALIMENTOS     93872
                         HIGIENE       33770
                         LIMPEZA       31509
                         BEBIDAS        9254
                         PET            6910
                         ACESSORIOS     3115
                         #N/D            776
Viúvo                    ALIMENTOS     10986
                         HIGIENE        3858
                         LIMPEZA        3696
                         BEBIDAS        1127
                         PET             814
                         ACESSORIOS      346
                         #N/D             73
Name: CO_ID, dtype: int64

🟢Sprint 6 (Versionamento): Envio dos arquivos (script + README.md + df_limpo), via Git para o repositório da turma no GitHub.

In [21]:
df_limpo = df_base_varejo_sem_duplicatas
df_limpo.to_csv("database\\df_limpo.csv", index=False)

df_limpo = pd.read_csv('database\\df_limpo.csv')
print(df_limpo.head(5).to_markdown(index=False))

| DATA       |   CO_ID |   CL_ID | CL_GENERO   |   CL_EC |   CL_FHL | CL_SEG   |   PR_ID | PR_CAT    | PR_NOME              | CL_EC_TEXT   |
|:-----------|--------:|--------:|:------------|--------:|---------:|:---------|--------:|:----------|:---------------------|:-------------|
| 2019-02-01 |    1000 |     534 | M           |       4 |        1 | C        |      67 | BEBIDAS   | REFRIGERANTE GUARANA | Solteiro     |
| 2019-02-01 |    1000 |     534 | M           |       4 |        1 | C        |      70 | BEBIDAS   | REFRIGERANTE OUTROS  | Solteiro     |
| 2019-02-01 |    1000 |     534 | M           |       4 |        1 | C        |     178 | HIGIENE   | LENCO UMEDECIDO      | Solteiro     |
| 2019-02-01 |    1000 |     534 | M           |       4 |        1 | C        |       4 | ALIMENTOS | ABACAXI              | Solteiro     |
| 2019-02-01 |    1000 |     534 | M           |       4 |        1 | C        |     175 | LIMPEZA   | LIMPADOR MULTIUSO    | Solteiro     |

🟢Sobre os problemas na base:

⚠️Dados vazios (#N/D): Tem muita categoria marcada como #N/D, o que tá atrapalhando nossa análise de mercado. Precisamos ver com o pessoal de dados o que tá acontecendo	com esse registro.

⚠️Limpeza geral: A extração ainda precisa de um pente fino. Tem muita duplicata e campo nulo que pode enviesar o resultado, então precisamos criar uma rotina de higienização melhor.

⚠️Falta de tempo: A base hoj só mostra o volume total, mas não temos o histórico. Sem saber a sazonalidade, fica difícil prever o que vem por ai.

===============================================================================
🟢Principais conclusões:

⭐Foco em Alimentos: A maior parte das vendas vem de alimentos, o que mostra que o pessoal prioriza itens essenciais e compra com frequência.

⭐Segmentação por perfil: Percebemos que casados costumam comprar bem mais itens para casa, o que é um prato cheio para campanhas mais direcionadas.

⭐Mix de produtos: Usar o ranking de vendas ajudou a bater o olho e ver o que realmente traz faturamento, ficando mais fácil decidir promoções e o que repor no estoque.